/**
 * Qeetrix typed token values — GENERATED by scripts/build-tokens.mjs.
 * Do not edit by hand. Edit tokens/** and rebuild.
 */

export const DURATION = {
  instant: 0,
  micro: 100,
  fast: 150,
  standard: 200,
  slow: 300,
  deliberate: 400,
  linger: 600,
} as const;

export const EASING = {
  standard: "cubic-bezier(0.4, 0, 0.2, 1)",
  decelerate: "cubic-bezier(0, 0, 0.2, 1)",
  accelerate: "cubic-bezier(0.4, 0, 1, 1)",
  sharp: "cubic-bezier(0.4, 0, 0.6, 1)",
  linear: "linear",
} as const;

export const ICON_SIZE = {
  xs: 14,
  sm: 16,
  md: 20,
  lg: 24,
} as const;

export const ICON_STROKE = {
  thin: 1.5,
  regular: 2,
} as const;

export const Z_INDEX = {
  base: 0,
  dropdown: 1000,
  sticky: 1100,
  fixed: 1200,
  modalBackdrop: 1300,
  modal: 1400,
  drawerBackdrop: 1500,
  drawer: 1600,
  popover: 1700,
  toast: 1800,
  commandPalette: 1900,
  tourBackdrop: 2000,
  tour: 2010,
  skipNav: 2100,
  debug: 9999,
} as const;

export const STATE_OPACITY = {
  disabled: 0.5,
} as const;

export const COMPONENT = {
  sidebar: {
    width: {
      default: "16rem",
      mobile: "18rem",
      icon: "3rem",
    },
  },
  tour: {
    cardWidth: "288px",
    offset: "12px",
  },
} as const;

export const SHADOW = {
  none: "none",
  insetSubtle: "inset 0 1px 3px rgb(0 0 0 / 0.08)",
  rest: "0 1px 2px -1px rgb(0 0 0 / 0.06), 0 2px 6px -2px rgb(0 0 0 / 0.07), 0 0 0 1px rgb(0 0 0 / 0.03)",
  hover:
    "0 2px 4px -2px rgb(0 0 0 / 0.07), 0 10px 20px -5px rgb(0 0 0 / 0.12), 0 0 0 1px rgb(0 0 0 / 0.03)",
  popover:
    "0 4px 10px -3px rgb(0 0 0 / 0.08), 0 14px 32px -8px rgb(0 0 0 / 0.16), 0 0 0 1px rgb(0 0 0 / 0.04)",
  modal:
    "0 10px 20px -6px rgb(0 0 0 / 0.12), 0 36px 64px -12px rgb(0 0 0 / 0.28), 0 0 0 1px rgb(0 0 0 / 0.04)",
} as const;

export const CHART_COLOR = {
  series1: "var(--chart-1)",
  series2: "var(--chart-2)",
  series3: "var(--chart-3)",
  series4: "var(--chart-4)",
  series5: "var(--chart-5)",
  series6: "var(--chart-6)",
  series7: "var(--chart-7)",
  series8: "var(--chart-8)",
  grid: "var(--chart-grid)",
  axis: "var(--chart-axis)",
  reference: "var(--chart-reference)",
  positive: "var(--chart-positive)",
  negative: "var(--chart-negative)",
  warning: "var(--chart-warning)",
} as const;
