/**
 * contract.mjs — validate the generated component manifest against the component contract.
 *
 * The contract is authored in TypeScript (src/contracts/, src/manifests/) and `tsc` already
 * rejects an invalid status or ARIA pattern in the registry. This is the second gate: it checks
 * the *generated* manifest — the artifact consumers actually read — against the same
 * vocabularies, and cross-checks it against scripts/config/category-map.json so metadata can
 * neither outlive its component nor go missing when one is added.
 *
 * `validateManifest` is a pure function over plain data so it can be exercised with synthetic
 * manifests; scripts/check/component-contract.mjs is the thin CLI over it, and
 * src/__tests__/component-contract.test.ts is where the negative cases live.
 *
 * Findings come in two severities:
 *   - **error**   — the manifest is wrong. Fails the gate.
 *   - **warning** — the manifest is valid but drifts from a convention (a non-standard `cva`
 *                   group, a size outside the recommended scale). Reported, never fatal:
 *                   Phase 1 does not break anything that already shipped.
 */

const MANIFEST_LOCATION = "component-manifest.json";
const REGISTRY_LOCATION = "src/manifests/component-registry.ts";

const isPlainObject = (value) =>
  typeof value === "object" && value !== null && !Array.isArray(value);
const isBoolean = (value) => typeof value === "boolean";
const isStringArrayOrNull = (value) =>
  value === null || (Array.isArray(value) && value.every((item) => typeof item === "string"));

const KEBAB_CASE = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

/** `alert-dialog` → `AlertDialog`. The manifest's `name` must be exactly this. */
export function pascalCase(slug) {
  return slug
    .split(/[-_]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

/**
 * Validate a manifest.
 *
 * @param {object}   input
 * @param {object}   input.manifest        the parsed component-manifest.json
 * @param {object}   input.vocabulary      the literal exports of src/contracts/
 * @param {object}   input.registry        COMPONENT_REGISTRY
 * @param {object}   input.registryDefaults REGISTRY_DEFAULTS
 * @param {object}   input.categoryMap     scripts/config/category-map.json
 * @param {number}   input.schemaVersion   MANIFEST_SCHEMA_VERSION
 * @returns {{ errors: object[], warnings: object[] }}
 */
export function validateManifest({
  manifest,
  vocabulary,
  registry = {},
  registryDefaults = {},
  categoryMap = {},
  schemaVersion,
}) {
  const errors = [];
  const warnings = [];

  const report =
    (list) =>
    (component, issue, extra = {}) =>
      list.push({ component, issue, location: MANIFEST_LOCATION, ...extra });
  const error = report(errors);
  const warn = report(warnings);

  const {
    COMPONENT_CATEGORIES,
    COMPONENT_STATUSES,
    COMPONENT_LAYERS,
    SUPPORT_LEVELS,
    SSR_SUPPORT_LEVELS,
    INTERACTION_STATES,
    ARIA_PATTERNS,
    VARIANT_GROUP_ALIASES,
    CANONICAL_VARIANTS,
    RECOMMENDED_SIZE_SCALE,
    A11Y_DIMENSIONS,
    A11Y_DIMENSION_STATES,
    A11Y_AUDIT_STATES,
    KEYBOARD_KEYS,
    FOCUS_MODELS,
    LIVE_REGION_POLITENESS,
  } = vocabulary;

  // ── the document itself ─────────────────────────────────────────────────────────────
  if (!Array.isArray(manifest.components)) {
    error(null, "manifest has no `components` array", {
      hint: "regenerate with `node scripts/build/manifest.mjs`",
    });
    return { errors, warnings };
  }

  if (schemaVersion !== undefined && manifest.schemaVersion !== schemaVersion) {
    error(null, `schemaVersion is ${manifest.schemaVersion}`, {
      expected: String(schemaVersion),
      hint: "the manifest was generated by an older script — regenerate it",
    });
  }

  if (manifest.count !== manifest.components.length) {
    error(null, `count is ${manifest.count} but there are ${manifest.components.length} entries`);
  }

  // The category vocabulary in the contract must match the category map on disk, or every
  // per-component category check below is validating against the wrong list.
  const mappedCategories = Object.keys(categoryMap).sort();
  if (mappedCategories.length > 0) {
    const declared = [...(COMPONENT_CATEGORIES ?? [])].sort();
    const missing = mappedCategories.filter((c) => !declared.includes(c));
    const extra = declared.filter((c) => !mappedCategories.includes(c));
    for (const category of missing) {
      error(null, `category "${category}" exists in category-map.json but not in the contract`, {
        location: "src/contracts/component.ts",
        hint: "add it to COMPONENT_CATEGORIES",
      });
    }
    for (const category of extra) {
      error(null, `contract declares category "${category}", which has no folder`, {
        location: "src/contracts/component.ts",
      });
    }
  }

  // ── per component ───────────────────────────────────────────────────────────────────
  const seenSlugs = new Map();
  const seenNames = new Map();
  const slugToCategory = new Map(
    Object.entries(categoryMap).flatMap(([category, slugs]) =>
      slugs.map((slug) => [slug, category]),
    ),
  );

  for (const [index, entry] of manifest.components.entries()) {
    const label = entry?.name ?? entry?.slug ?? `components[${index}]`;

    if (!isPlainObject(entry)) {
      error(label, "entry is not an object");
      continue;
    }

    // identity
    if (typeof entry.slug !== "string" || !KEBAB_CASE.test(entry.slug)) {
      error(label, `slug "${entry.slug}" is not kebab-case`);
    } else if (seenSlugs.has(entry.slug)) {
      error(label, `duplicate registration — slug "${entry.slug}" appears twice`, {
        hint: `first seen at components[${seenSlugs.get(entry.slug)}]`,
      });
    } else {
      seenSlugs.set(entry.slug, index);
    }

    if (typeof entry.name !== "string" || entry.name.length === 0) {
      error(label, "name is missing");
    } else {
      if (typeof entry.slug === "string" && entry.name !== pascalCase(entry.slug)) {
        error(label, `name "${entry.name}" does not match its slug`, {
          expected: pascalCase(entry.slug),
        });
      }
      if (seenNames.has(entry.name)) {
        error(label, `duplicate registration — name "${entry.name}" appears twice`, {
          hint: `first seen at components[${seenNames.get(entry.name)}]`,
        });
      } else {
        seenNames.set(entry.name, index);
      }
    }

    // category + layer
    if (!(COMPONENT_CATEGORIES ?? []).includes(entry.category)) {
      error(label, `category "${entry.category}" is not a valid category`, {
        expected: `one of ${(COMPONENT_CATEGORIES ?? []).join(", ")}`,
      });
    } else if (slugToCategory.size > 0 && slugToCategory.get(entry.slug) !== entry.category) {
      error(label, `category "${entry.category}" disagrees with category-map.json`, {
        expected: slugToCategory.get(entry.slug) ?? "(not listed at all)",
        location: "scripts/config/category-map.json",
      });
    }
    if (!(COMPONENT_LAYERS ?? []).includes(entry.layer)) {
      error(label, `layer "${entry.layer}" is not a component layer`, {
        expected: `one of ${(COMPONENT_LAYERS ?? []).join(", ")}`,
      });
    }

    // status
    if (!(COMPONENT_STATUSES ?? []).includes(entry.status)) {
      error(label, `status "${entry.status}" is not a valid status`, {
        expected: `one of ${(COMPONENT_STATUSES ?? []).join(", ")}`,
        location: REGISTRY_LOCATION,
      });
    }

    // capabilities
    if (!isPlainObject(entry.capabilities)) {
      error(label, "capabilities block is missing");
    } else {
      for (const capability of ["rtl", "darkMode", "density", "reducedMotion"]) {
        const value = entry.capabilities[capability];
        if (!(SUPPORT_LEVELS ?? []).includes(value)) {
          error(label, `capabilities.${capability} is "${value}"`, {
            expected: `one of ${(SUPPORT_LEVELS ?? []).join(", ")}`,
          });
        }
      }
      if (!(SSR_SUPPORT_LEVELS ?? []).includes(entry.capabilities.ssr)) {
        error(label, `capabilities.ssr is "${entry.capabilities.ssr}"`, {
          expected: `one of ${(SSR_SUPPORT_LEVELS ?? []).join(", ")}`,
        });
      }
    }

    // states
    if (!Array.isArray(entry.states)) {
      error(label, "states is not an array");
    } else {
      const seen = new Set();
      for (const state of entry.states) {
        if (!(INTERACTION_STATES ?? []).includes(state)) {
          error(label, `states contains "${state}", which is not an interaction state`, {
            expected: `one of ${(INTERACTION_STATES ?? []).join(", ")}`,
          });
        }
        if (seen.has(state)) error(label, `states lists "${state}" twice`);
        seen.add(state);
      }
    }

    // accessibility — the two consistency rules
    if (!isPlainObject(entry.accessibility)) {
      error(label, "accessibility block is missing");
    } else {
      const { required, pattern } = entry.accessibility;
      if (!isBoolean(required)) {
        error(label, `accessibility.required is "${required}"`, { expected: "true or false" });
      }
      if (pattern !== null && !(ARIA_PATTERNS ?? []).includes(pattern)) {
        error(label, `accessibility.pattern "${pattern}" is not a known ARIA pattern`, {
          expected: `one of ${(ARIA_PATTERNS ?? []).join(", ")}`,
          location: REGISTRY_LOCATION,
        });
      }
      if (required === true && pattern === null) {
        error(label, "Missing accessibility.pattern", {
          expected: 'an APG pattern name, or "none" when no pattern applies',
          location: REGISTRY_LOCATION,
          hint: "a component with required: true has an accessibility contract to name",
        });
      }
      // ── the audit matrix ────────────────────────────────────────────────────────
      if (!(A11Y_AUDIT_STATES ?? []).includes(entry.accessibility.audit)) {
        error(label, `accessibility.audit is "${entry.accessibility.audit}"`, {
          expected: `one of ${(A11Y_AUDIT_STATES ?? []).join(", ")}`,
        });
      }
      if (!isPlainObject(entry.accessibility.dimensions)) {
        error(label, "accessibility.dimensions block is missing");
      } else {
        for (const dimension of A11Y_DIMENSIONS ?? []) {
          const state = entry.accessibility.dimensions[dimension];
          if (!(A11Y_DIMENSION_STATES ?? []).includes(state)) {
            error(label, `accessibility.dimensions.${dimension} is "${state}"`, {
              expected: `one of ${(A11Y_DIMENSION_STATES ?? []).join(", ")}`,
            });
          }
          // A gap without a reason is a defect wearing a label.
          if (
            (state === "exception" || state === "partial") &&
            !entry.accessibility.exceptions?.[dimension]
          ) {
            error(label, `accessibility.dimensions.${dimension} is "${state}" with no reason`, {
              expected: `an entry in accessibility.exceptions.${dimension}`,
              location: REGISTRY_LOCATION,
            });
          }
        }
        // The roll-up is computed, so it must actually agree with the dimensions it summarises.
        const states = Object.values(entry.accessibility.dimensions);
        const expectedAudit = states.includes("not-audited")
          ? "not-audited"
          : states.includes("exception")
            ? "exception"
            : states.includes("partial")
              ? "partial"
              : "audited";
        if (entry.accessibility.audit !== expectedAudit) {
          error(label, `accessibility.audit says "${entry.accessibility.audit}"`, {
            expected: expectedAudit,
            hint: "the roll-up is computed from the dimensions — regenerate the manifest",
          });
        }
      }

      for (const key of entry.accessibility.keyboard ?? []) {
        if (!(KEYBOARD_KEYS ?? []).includes(key)) {
          error(label, `accessibility.keyboard lists "${key}", which is not a known key`, {
            expected: `one of ${(KEYBOARD_KEYS ?? []).join(", ")}`,
            location: REGISTRY_LOCATION,
          });
        }
      }
      if (entry.accessibility.focus !== null && entry.accessibility.focus !== undefined) {
        const focus = entry.accessibility.focus;
        if (!(FOCUS_MODELS ?? []).includes(focus.model)) {
          error(label, `accessibility.focus.model is "${focus.model}"`, {
            expected: `one of ${(FOCUS_MODELS ?? []).join(", ")}`,
            location: REGISTRY_LOCATION,
          });
        }
        for (const field of ["contained", "restored"]) {
          if (!isBoolean(focus[field])) {
            error(label, `accessibility.focus.${field} must be true or false`, {
              location: REGISTRY_LOCATION,
            });
          }
        }
        // A trap the user cannot get out of is the defect this pairing prevents.
        if (focus.contained === true && focus.restored !== true) {
          error(label, "contains focus but does not restore it", {
            expected: "restored: true",
            hint: "a modal that traps focus and does not give it back strands the keyboard user",
            location: REGISTRY_LOCATION,
          });
        }
      }
      const politeness = entry.accessibility.liveRegion;
      if (politeness !== null && politeness !== undefined) {
        if (!(LIVE_REGION_POLITENESS ?? []).includes(politeness)) {
          error(label, `accessibility.liveRegion is "${politeness}"`, {
            expected: `one of ${(LIVE_REGION_POLITENESS ?? []).join(", ")}`,
            location: REGISTRY_LOCATION,
          });
        }
      }

      if (typeof pattern === "string" && pattern !== "none" && required !== true) {
        error(label, `accessibility.pattern is "${pattern}" but required is false`, {
          expected: "required: true",
          location: REGISTRY_LOCATION,
          hint: "implementing an APG pattern is a contract; changes to it are breaking",
        });
      }
    }

    // testing — every field is derived, so a missing one means a broken generator
    if (!isPlainObject(entry.testing)) {
      error(label, "testing block is missing");
    } else {
      for (const gate of ["unit", "accessibility", "interaction", "visual", "hydration"]) {
        if (!isBoolean(entry.testing[gate])) {
          error(label, `testing.${gate} is "${entry.testing[gate]}"`, {
            expected: "true or false",
          });
        }
      }
    }

    // api / variants
    if (!isPlainObject(entry.api)) {
      error(label, "api block is missing");
    } else {
      for (const field of ["variants", "sizes", "variantGroups", "domainAxes"]) {
        if (!isStringArrayOrNull(entry.api[field])) {
          error(label, `api.${field} must be an array of strings or null`);
        }
      }
      // Structural: a malformed or repeated variant name is a real mistake.
      for (const field of ["variants", "sizes", "variantGroups"]) {
        const values = entry.api[field];
        if (!Array.isArray(values)) continue;
        const seen = new Set();
        for (const value of values) {
          if (typeof value !== "string" || value.length === 0) continue;
          if (seen.has(value)) error(label, `api.${field} lists "${value}" twice`);
          seen.add(value);
        }
      }
      // ── the shared vocabularies ───────────────────────────────────────────────────
      const aliases = entry.api.variantAliases ?? {};
      const domainAxes = entry.api.domainAxes ?? [];

      for (const [alias, canonical] of Object.entries(aliases)) {
        if (!(entry.api.variants ?? []).includes(alias)) {
          error(
            label,
            `declares "${alias}" as a variant alias, but the component has no such variant`,
            {
              location: REGISTRY_LOCATION,
            },
          );
        }
        if (!(entry.api.variants ?? []).includes(canonical)) {
          error(
            label,
            `aliases "${alias}" to "${canonical}", which the component does not accept`,
            {
              expected: `add "${canonical}" to the cva variants`,
              location: REGISTRY_LOCATION,
            },
          );
        }
        if (!(CANONICAL_VARIANTS ?? []).includes(canonical)) {
          error(label, `aliases "${alias}" to "${canonical}", which is not a canonical variant`, {
            expected: `one of ${(CANONICAL_VARIANTS ?? []).join(", ")}`,
            location: REGISTRY_LOCATION,
          });
        }
      }

      if (!domainAxes.includes("variant")) {
        for (const variant of entry.api.variants ?? []) {
          if ((INTERACTION_STATES ?? []).includes(variant)) {
            error(label, `has a variant named "${variant}", which is an interaction state`, {
              expected: `a boolean prop such as \`${variant}\``,
              hint: "variant is what a component looks like; state is what it is currently doing",
            });
          } else if (
            !(CANONICAL_VARIANTS ?? []).includes(variant) &&
            aliases[variant] === undefined
          ) {
            error(
              label,
              `has a variant named "${variant}", which is not in the shared vocabulary`,
              {
                expected: `one of ${(CANONICAL_VARIANTS ?? []).join(", ")}`,
                location: REGISTRY_LOCATION,
                hint: 'declare it in api.variantAliases if it is a legacy name, or api.domainAxes: ["variant"] if the names are domain concepts',
              },
            );
          }
        }
      }

      if (!domainAxes.includes("size")) {
        for (const size of entry.api.sizes ?? []) {
          if (!(RECOMMENDED_SIZE_SCALE ?? []).includes(size)) {
            error(label, `has a size named "${size}", which is not on the size scale`, {
              expected: `one of ${(RECOMMENDED_SIZE_SCALE ?? []).join(", ")}`,
              location: REGISTRY_LOCATION,
              hint: 'declare api.domainAxes: ["size"] when the names are domain concepts',
            });
          }
        }
        // `default` and `md` both name the middle of the scale; a component with both is a
        // coin toss for the consumer.
        const sizes = new Set(entry.api.sizes ?? []);
        if (sizes.has("default") && sizes.has("md")) {
          error(label, 'declares both "default" and "md" sizes', {
            expected: 'one of them — "default" when the size is density-resolved, "md" otherwise',
          });
        }
      }

      // ── controlled state ─────────────────────────────────────────────────────────
      for (const triple of entry.api.controlled ?? []) {
        for (const field of ["value", "default", "change"]) {
          if (typeof triple[field] !== "string" || triple[field].length === 0) {
            error(label, `has a controlled-state declaration missing \`${field}\``, {
              location: REGISTRY_LOCATION,
            });
          }
        }
        if (typeof triple.value !== "string") continue;
        const capitalised = triple.value.charAt(0).toUpperCase() + triple.value.slice(1);
        if (triple.default !== `default${capitalised}`) {
          error(label, `controls "${triple.value}" but seeds it with "${triple.default}"`, {
            expected: `default${capitalised}`,
            hint: "the triple is x / default<X> / on<X>Change, so a consumer can predict it",
          });
        }
        if (triple.change !== `on${capitalised}Change`) {
          error(label, `controls "${triple.value}" but reports it with "${triple.change}"`, {
            expected: `on${capitalised}Change`,
          });
        }
      }

      // Convention: the visual and size axes have one name each in this library.
      for (const group of entry.api.variantGroups ?? []) {
        const canonical = VARIANT_GROUP_ALIASES?.[group];
        if (canonical !== undefined) {
          warn(label, `cva group "${group}" duplicates an existing concept`, {
            expected: `"${canonical}"`,
            location: `src/components/${entry.category}/${entry.slug}.tsx`,
            hint: "one name per axis keeps the prop surface predictable across the library",
          });
        }
      }
    }

    // deprecation — status and record must agree, in both directions
    const { deprecation } = entry;
    if (entry.status === "deprecated") {
      if (!isPlainObject(deprecation)) {
        error(label, "status is deprecated but there is no deprecation record", {
          expected: "{ since, reason, replacement, migration, removeIn }",
          location: REGISTRY_LOCATION,
        });
      } else {
        for (const field of ["since", "reason"]) {
          if (typeof deprecation[field] !== "string" || deprecation[field].length === 0) {
            error(label, `deprecation.${field} is missing`, { location: REGISTRY_LOCATION });
          }
        }
        for (const field of ["replacement", "migration", "removeIn"]) {
          if (!(deprecation[field] === null || typeof deprecation[field] === "string")) {
            error(label, `deprecation.${field} must be a string or null`, {
              location: REGISTRY_LOCATION,
            });
          }
        }
      }
    } else if (deprecation !== null && deprecation !== undefined) {
      error(label, `has a deprecation record but status is "${entry.status}"`, {
        expected: 'status: "deprecated"',
        location: REGISTRY_LOCATION,
      });
    }

    // the schema-v1 mirrors must keep telling the truth
    if (isBoolean(entry.deprecated) && entry.deprecated !== (entry.status === "deprecated")) {
      error(
        label,
        `legacy \`deprecated\` flag is ${entry.deprecated} but status is "${entry.status}"`,
        {
          hint: 'an @deprecated marker in the source needs status: "deprecated" in the registry',
          location: REGISTRY_LOCATION,
        },
      );
    }
    if (isPlainObject(entry.testing)) {
      if (isBoolean(entry.tested) && entry.tested !== entry.testing.unit) {
        error(label, "legacy `tested` flag disagrees with testing.unit");
      }
      if (isBoolean(entry.story) && entry.story !== entry.testing.visual) {
        error(label, "legacy `story` flag disagrees with testing.visual");
      }
    }
  }

  // ── tallies ─────────────────────────────────────────────────────────────────────────
  const tally = (field, keyOf) => {
    if (!isPlainObject(manifest[field])) return;
    for (const [key, value] of Object.entries(manifest[field])) {
      const actual = manifest.components.filter((entry) => keyOf(entry) === key).length;
      if (value !== actual) {
        error(null, `${field}.${key} is ${value} but ${actual} components match`);
      }
    }
  };
  tally("categories", (entry) => entry.category);
  tally("statuses", (entry) => entry.status);

  // ── registry ↔ filesystem ───────────────────────────────────────────────────────────
  for (const slug of Object.keys(registry)) {
    if (!seenSlugs.has(slug)) {
      error(pascalCase(slug), "is declared in the registry but there is no such component", {
        location: REGISTRY_LOCATION,
        hint: "remove the entry, or restore the component",
      });
    }
  }
  for (const slug of slugToCategory.keys()) {
    if (!seenSlugs.has(slug)) {
      error(pascalCase(slug), "is in category-map.json but missing from the manifest", {
        hint: "regenerate with `node scripts/build/manifest.mjs`",
      });
    }
  }
  if (registryDefaults.status !== undefined && registryDefaults.accessibility === undefined) {
    error(null, "REGISTRY_DEFAULTS has no accessibility block", { location: REGISTRY_LOCATION });
  }

  return { errors, warnings };
}

/** Render one finding in the shape a developer can act on without opening anything else. */
export function formatFinding(finding, severity = "Error") {
  const lines = [`Component Contract ${severity}`, ""];
  if (finding.component) lines.push(`Component: ${finding.component}`, "");
  lines.push("Issue:", `  ${finding.issue}`);
  if (finding.expected) lines.push("", "Expected:", `  ${finding.expected}`);
  if (finding.hint) lines.push("", "Why:", `  ${finding.hint}`);
  lines.push("", "Location:", `  ${finding.location}`);
  return lines.join("\n");
}
