/**
 * Generates src/brand/logos/qeet-logo-on-{light,dark}.tsx from the raw brand SVGs
 * in src/brand/assets/raw. The inner SVG markup is embedded verbatim and rendered
 * via dangerouslySetInnerHTML (trusted, static art) so the components stay
 * server-safe (no "use client") and we never hand-convert path data.
 *
 * The shared mask id ("qBowlHole") is suffixed per variant to avoid collisions
 * when both variants render on the same page (adaptive <QeetLogo/>).
 *
 * Re-run with: bun run --filter @qeetrix/ui generate-logos
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const PKG = join(dirname(fileURLToPath(import.meta.url)), "..");

const VARIANTS = [
  { file: "qeet-logo-on-light.svg", name: "QeetLogoOnLight", suffix: "onlight" },
  { file: "qeet-logo-on-dark.svg", name: "QeetLogoOnDark", suffix: "ondark" },
];

for (const { file, name, suffix } of VARIANTS) {
  const raw = readFileSync(join(PKG, "src/brand/assets/raw", file), "utf8");

  const viewBox = raw.match(/viewBox="([^"]+)"/)?.[1] ?? "0 0 1254 1254";

  let inner = raw
    .replace(/^[\s\S]*?<svg[^>]*>/, "") // drop everything up to and incl <svg ...>
    .replace(/<\/svg>\s*$/, "") // drop closing </svg>
    .replace(/<title>[\s\S]*?<\/title>/g, "") // drop baked-in title; we set aria-label
    .replaceAll("qBowlHole", `qBowlHole-${suffix}`) // unique mask id per variant
    .trim();

  // safe to embed in a template literal
  inner = inner.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

  const tsx = `/* GENERATED by scripts/generate-logos.mjs from src/brand/assets/raw/${file}. Do not edit by hand. */
import type { SVGProps } from "react";

const INNER = \`${inner}\`;

export interface QeetLogoVariantProps extends Omit<SVGProps<SVGSVGElement>, "dangerouslySetInnerHTML"> {
  /** Width and height in px (the mark is square). Defaults to 32. */
  size?: number | string;
  /** Accessible label. Defaults to "Qeet". Pass \`null\` to mark decorative. */
  title?: string | null;
}

/** Qeet mark — ${suffix === "onlight" ? "dark artwork, for use on LIGHT surfaces" : "light artwork, for use on DARK surfaces"}. */
export function ${name}({ size = 32, title = "Qeet", ...props }: QeetLogoVariantProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="${viewBox}"
      width={size}
      height={size}
      role={title === null ? undefined : "img"}
      aria-label={title === null ? undefined : title}
      aria-hidden={title === null ? true : undefined}
      dangerouslySetInnerHTML={{ __html: INNER }}
      {...props}
    />
  );
}
`;

  writeFileSync(
    join(
      PKG,
      "src/brand/logos",
      `${name === "QeetLogoOnLight" ? "qeet-logo-on-light" : "qeet-logo-on-dark"}.tsx`,
    ),
    tsx,
  );
  console.log(
    `✔ generated src/brand/logos/${name === "QeetLogoOnLight" ? "qeet-logo-on-light" : "qeet-logo-on-dark"}.tsx`,
  );
}
